parameters:
  runIntegrationTests:

steps:
- displayName: Use Python $(python.version)
  task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    architecture: '$(python.architecture)'

- displayName: Setup RAMDisk
  task: PowerShell@2
  inputs:
    filePath: .azure-pipelines/scripts/New-RAMDisk.ps1
    arguments: "-Drive R -Size 1GB"

- displayName: Set RAMDisk Permissions
  powershell: |
    mkdir R:\Temp
    $acl = Get-Acl "R:\Temp"
    $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
        "Everyone", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow"
    )
    $acl.AddAccessRule($rule)
    Set-Acl "R:\Temp" $acl

- displayName: Install Tox
  bash: pip install --upgrade 'virtualenv<20' setuptools tox

- displayName: Run unit tests
  script: tox -e py -- -m unit -n auto --junit-xml=junit/unit-test.xml
  env:
    TEMP: "R:\\Temp"

- ${{ if eq(parameters.runIntegrationTests, 'true') }}:
  - displayName: Run integration tests
    powershell: |
      # Fix Git SSL errors
      pip install certifi tox
      python -m certifi > cacert.txt
      $env:GIT_SSL_CAINFO = $(Get-Content cacert.txt)

      # Shorten paths to get under MAX_PATH or else integration tests will fail
      # https://bugs.python.org/issue18199
      $env:TEMP = "R:\Temp"

      tox -e py -- -m integration -n auto --duration=5 --junit-xml=junit/integration-test.xml

- displayName: Publish Test Results
  task: PublishTestResults@2
  inputs:
    testResultsFiles: junit/*.xml
    testRunTitle: 'Python $(python.version)'
  condition: succeededOrFailed()
