parameters:
  vmImage:
  osName:

jobs:
- job: Test_Primary_${{ parameters.osName }}_one
  displayName: Tests / ${{ parameters.osName }} /

  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      "2.7-x86 / 1":
        python.version: '2.7'
        python.architecture: x86
      "2.7 / 1":
        python.version: '2.7'
        python.architecture: x64
      "3.8 / 1":
        python.version: '3.8'
        python.architecture: x64

  steps:
  - template: ../steps/run-tests-windows.yml
    parameters:
      testGroup: one

- job: Test_Primary_${{ parameters.osName }}_two
  displayName: Tests / ${{ parameters.osName }} /

  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      "2.7-x86 / 2":
        python.version: '2.7'
        python.architecture: x86
      "2.7 / 2":
        python.version: '2.7'
        python.architecture: x64
      "3.8 / 2":
        python.version: '3.8'
        python.architecture: x64

  steps:
  - template: ../steps/run-tests-windows.yml
    parameters:
      testGroup: two

- job: Test_Secondary_${{ parameters.osName }}
  displayName: Tests / ${{ parameters.osName }} /
  # Don't run integration tests for these runs
  # Run after Test_Primary_* so we don't devour time and jobs.
  dependsOn:
  - Test_Primary_${{ parameters.osName }}_one
  - Test_Primary_${{ parameters.osName }}_two

  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      "3.5":
        python.version: '3.5'
        python.architecture: x64
      "3.6":
        python.version: '3.6'
        python.architecture: x64
      "3.7":
        python.version: '3.7'
        python.architecture: x64
      "3.5-x86":
        python.version: '3.5'
        python.architecture: x86
      "3.6-x86":
        python.version: '3.6'
        python.architecture: x86
      "3.7-x86":
        python.version: '3.7'
        python.architecture: x86
      "3.8-x86":
        python.version: '3.8'
        python.architecture: x86

  steps:
  - template: ../steps/run-tests-windows.yml
    parameters:
      testGroup: unit
