name: CI

on:
  push:
    branches: [master]
    tags:
      # Tags for all potential release numbers till 2030.
      - "2[0-9].[0-3]" # 20.0 -> 29.3
      - "2[0-9].[0-3].[0-9]+" # 20.0.0 -> 29.3.[0-9]+
  pull_request:
  schedule:
    - cron: 0 0 * * MON # Run every Monday at 00:00 UTC

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0

  packaging:
    name: packaging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - run: pip install tox nox

      - run: tox -e docs
      - run: tox -e vendoring

      - name: Set up git credentials
        run: |
          git config --global user.email "pypa-dev@googlegroups.com"
          git config --global user.name "pip"

      - run: nox -s prepare-release -- 99.9
      - run: nox -s build-release -- 99.9

  tests-unix:
    name: tests / ${{ matrix.python }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest

    needs: [pre-commit, packaging]

    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu, MacOS]
        python: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - run: pip install tox 'virtualenv<20'

      # Main check
      - name: Run unit tests
        run: >-
          tox -e py --
          -m unit
          --verbose --numprocesses auto --showlocals
      - name: Run integration tests
        run: >-
          tox -e py --
          -m integration
          --verbose --numprocesses auto --showlocals
          --durations=5

  tests-windows:
    name: tests / ${{ matrix.python }} / ${{ matrix.os }} / ${{ matrix.group }}
    runs-on: ${{ matrix.os }}-latest

    needs: [pre-commit, packaging]

    strategy:
      fail-fast: false
      matrix:
        os: [Windows]
        python: [3.6, 3.7, 3.8, 3.9]
        group: [1, 2]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      # We use a RAMDisk on Windows, since filesystem IO is a big slowdown
      # for our tests.
      - name: Create a RAMDisk
        run: ./tools/ci/New-RAMDisk.ps1 -Drive R -Size 1GB

      - name: Setup RAMDisk permissions
        run: |
          mkdir R:\Temp
          $acl = Get-Acl "R:\Temp"
          $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
              "Everyone", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow"
          )
          $acl.AddAccessRule($rule)
          Set-Acl "R:\Temp" $acl

      - run: pip install tox 'virtualenv<20'
        env:
          TEMP: "R:\\Temp"

      # Main check
      - name: Run unit tests
        if: matrix.group == 1
        run: >-
          tox -e py --
          -m unit
          --verbose --numprocesses auto --showlocals
        env:
          TEMP: "R:\\Temp"

      - name: Run integration tests (group 1)
        if: matrix.group == 1
        run: >-
          tox -e py --
          -m integration -k "not test_install"
          --verbose --numprocesses auto --showlocals
        env:
          TEMP: "R:\\Temp"

      - name: Run integration tests (group 2)
        if: matrix.group == 2
        run: >-
          tox -e py --
          -m integration -k "test_install"
          --verbose --numprocesses auto --showlocals
        env:
          TEMP: "R:\\Temp"
